-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-10-21 21:37:26 EEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE customer (
    customer_id  INTEGER NOT NULL,
    first_name   VARCHAR2(20) NOT NULL,
    last_name    VARCHAR2(20) NOT NULL,
    phone_number VARCHAR2(13) NOT NULL UNIQUE
);

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );

CREATE TABLE employee (
    employee_id  INTEGER NOT NULL,
    first_name   VARCHAR2(55) NOT NULL,
    last_name    VARCHAR2(20) NOT NULL,
    phone_number VARCHAR2(13) NOT NULL UNIQUE,
    position_id  INTEGER NOT NULL
);

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( employee_id );

CREATE TABLE "GROUP" (
    group_id INTEGER NOT NULL,
    name     VARCHAR2(15) NOT NULL UNIQUE
);

ALTER TABLE "GROUP" ADD CONSTRAINT group_pk PRIMARY KEY ( group_id );

CREATE TABLE inventory (
    inventory_id INTEGER NOT NULL,
    quantity     INTEGER NOT NULL,
    price        NUMBER NOT NULL,
    import_date  DATE NOT NULL,
    product_id   INTEGER NOT NULL
);

ALTER TABLE inventory ADD CONSTRAINT inventory_pk PRIMARY KEY ( inventory_id );

CREATE TABLE inventory_sale (
    inventory_sale_id INTEGER NOT NULL,
    sold_quantity     INTEGER NOT NULL,
    inventory_id      INTEGER NOT NULL,
    sale_id           INTEGER NOT NULL
);

ALTER TABLE inventory_sale ADD CONSTRAINT inventory_sale_pk PRIMARY KEY ( inventory_sale_id );

CREATE TABLE position (
    position_id INTEGER NOT NULL,
    name        VARCHAR2(65) NOT NULL UNIQUE
);

ALTER TABLE position ADD CONSTRAINT position_pk PRIMARY KEY ( position_id );

CREATE TABLE product (
    product_id INTEGER NOT NULL,
    name       VARCHAR2(255) NOT NULL,
    group_id   INTEGER NOT NULL
);

ALTER TABLE product ADD CONSTRAINT product_pk PRIMARY KEY ( product_id );

CREATE TABLE sale (
    sale_id     INTEGER NOT NULL,
    "date"      DATE NOT NULL,
    customer_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL
);

ALTER TABLE sale ADD CONSTRAINT sale_pk PRIMARY KEY ( sale_id );

ALTER TABLE employee
    ADD CONSTRAINT employee_position_fk FOREIGN KEY ( position_id )
        REFERENCES position ( position_id );

ALTER TABLE inventory
    ADD CONSTRAINT inventory_product_fk FOREIGN KEY ( product_id )
        REFERENCES product ( product_id );

ALTER TABLE inventory_sale
    ADD CONSTRAINT inventory_sale_inventory_fk FOREIGN KEY ( inventory_id )
        REFERENCES inventory ( inventory_id );

ALTER TABLE inventory_sale
    ADD CONSTRAINT inventory_sale_sale_fk FOREIGN KEY ( sale_id )
        REFERENCES sale ( sale_id );

ALTER TABLE product
    ADD CONSTRAINT product_group_fk FOREIGN KEY ( group_id )
        REFERENCES "GROUP" ( group_id );

ALTER TABLE sale
    ADD CONSTRAINT sale_customer_fk FOREIGN KEY ( customer_id )
        REFERENCES customer ( customer_id );

ALTER TABLE sale
    ADD CONSTRAINT sale_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );
