version: '3'
services:
  app:
    container_name: 21621577.app
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
  db:
    container_name: 21621577.db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: yavor
      POSTGRES_PASSWORD: it*
      POSTGRES_DB: tasks-manager

