DROP TABLE ProductTags;
DROP TABLE ProductImages;
DROP TABLE Tags;
DROP TABLE ProductInventory;
DROP TABLE SaleItems;
DROP TABLE Sales;
DROP TABLE Products;
DROP TABLE Categories;
DROP TABLE __EFMigrationsHistory;
